import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main IME docs. Installation guides are nested under one category so platforms
  // remain easy to scan without flattening the main navigation.
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tổng quan cài đặt',
      link: {type: 'doc', id: 'install/index'},
      collapsed: false,
      items: ['install/ios', 'install/android', 'install/macos', 'install/windows', 'install/linux'],
    },
    'input-methods/vietnamese',
  ],

  // Funput Term (the terminal wrapper) — its own section/menu.
  funputTermSidebar: [{type: 'autogenerated', dirName: 'funput-term'}],
};

export default sidebars;
