import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main IME docs: intro + the autogenerated install guides. Scoped explicitly (not
  // dirName '.') so the Funput Term docs live in their own sidebar/menu instead.
  tutorialSidebar: ['intro', {type: 'autogenerated', dirName: 'install'}],

  // Funput Term (the terminal wrapper) — its own section/menu.
  funputTermSidebar: [{type: 'autogenerated', dirName: 'funput-term'}],
};

export default sidebars;
